import { withoutElevatorEndpointSpawns } from "./terrain-elevator";
import { loadWorkerTelescopeModules } from "./load-worker-telescope";
import { installTelescopeShim } from "./telescope-dom-shim";
import { installFetchInterceptor, installImageSrcInterceptor } from "./telescope-data-bridge";

// Setup fake DOM and Window for telescope exports
if (typeof document === "undefined") {
  (globalThis as any).document = {
    createElement: (tag: string) => {
      const el: any = { style: {}, children: [] };
      el.appendChild = (child: any) => el.children.push(child);
      el.setAttribute = () => {};
      el.remove = () => {};
      return el;
    },
    getElementById: () => null,
    body: {
      appendChild: () => {}
    }
  };
}
if (typeof window === "undefined") {
  (globalThis as any).window = self;
}

// We MUST install shims synchronously BEFORE any dynamic imports hit top-level await!
installTelescopeShim();
installFetchInterceptor();
installImageSrcInterceptor();

self.onmessage = async (e) => {
  let phase = "initializing worker modules";
  try {
    const { biomeData, tileSpawns, seed, ngPlus, pw, gameMode, perks, skipCosmeticScenes, unlocks, dailySeed, elevatorColumns = [], elevatorSpawns = [] } = e.data;

    // Install matching runtime-data routes before evaluating either fork.
    installFetchInterceptor(!!e.data.fullPixels);
    const modules = await loadWorkerTelescopeModules(!!e.data.fullPixels);
    const { scanSpawnFunctions, getSpecialPoIs } = modules.poiScannerMod;
    const { addStaticPixelScenes } = modules.staticSpawnsMod;
    const { updateSettings } = modules.settingsMod;
    const { loadPixelSceneData } = modules.pixelSceneMod;
    const { setUnlocks, UNLOCKABLES } = modules.unlocksMod;

    // Mirror telescope-adapter's setUnlocks logic so side PWs roll wand/chest
    // spell pools against the same unlock set as PW 0.
    if (dailySeed || unlocks == null) {
      setUnlocks(Object.keys(UNLOCKABLES));
    } else {
      setUnlocks(unlocks);
    }

    // Initialize required telescope settings — must mirror the main-thread
    // init in telescope-adapter.ts. Missing `showEnemies: true` here was why
    // creatures did not spawn in side PWs generated by this worker.
    updateSettings({
      gameMode,
      skipCosmeticScenes,
      clearSpawnPixels: true,
      recolorMaterials: true,
      enableEdgeNoise: true,
      fixHolyMountainEdgeNoise: true,
      enableStaticPixelScenes: 'all',
      excludeTaikasauva: false,
      excludeEdgeCases: false,
      showEnemies: true,
    });

    // Populate worker's pixel scene cache before performing generation
    phase = "loading pixel scenes";
    await loadPixelSceneData();

    phase = "scanning main-plane spawns";
    // 1. Scan spawns
    const scanResults = scanSpawnFunctions(biomeData, tileSpawns, seed, ngPlus, pw, 0, skipCosmeticScenes, perks, gameMode);
    
    // 2. Special POIs
    const specialPOIs = getSpecialPoIs(biomeData, seed, ngPlus, pw, 0, perks, gameMode);
    
    // 3. Static Pixel Scenes
    const staticResults = addStaticPixelScenes(seed, ngPlus, pw, 0, biomeData, false, perks, false, gameMode);

    let combinedPois = scanResults.generatedSpawns.concat(specialPOIs);
    let pixelScenes = scanResults.finalPixelScenes;

    if (staticResults && staticResults.pois) {
      combinedPois.push(...staticResults.pois);
    }
    if (staticResults && staticResults.pixelScenes) {
      pixelScenes = pixelScenes.concat(staticResults.pixelScenes);
    }

    // 4. Vertical PWs (sky/hell)
    const verticalPois = [];
    for (const pvt of [-1, 1]) {
      phase = `scanning vertical plane ${pvt}`;
      const vtSpecial = getSpecialPoIs(biomeData, seed, ngPlus, pw, pvt, perks, gameMode);
      if (vtSpecial && vtSpecial.length > 0) {
        verticalPois.push(...vtSpecial);
      }

      const vtSources = pvt === 1 ? withoutElevatorEndpointSpawns(tileSpawns, elevatorColumns, biomeData.pixels.length / 48) : tileSpawns;
      const vtScan = scanSpawnFunctions(biomeData, vtSources, seed, ngPlus, pw, pvt, skipCosmeticScenes, perks, gameMode);
      if (pvt === 1 && elevatorSpawns.length) {
        const shaftScan = scanSpawnFunctions(biomeData, elevatorSpawns, seed, ngPlus, pw, 0, skipCosmeticScenes, perks, gameMode);
        vtScan.generatedSpawns.push(...shaftScan.generatedSpawns);
        vtScan.finalPixelScenes.push(...shaftScan.finalPixelScenes);
      }
      if (vtScan.generatedSpawns && vtScan.generatedSpawns.length > 0) {
        verticalPois.push(...vtScan.generatedSpawns);
      }
      if (vtScan.finalPixelScenes && vtScan.finalPixelScenes.length > 0) {
        pixelScenes = pixelScenes.concat(vtScan.finalPixelScenes);
      }

      const vtResults = addStaticPixelScenes(seed, ngPlus, pw, pvt, biomeData, false, perks, false, gameMode);
      if (vtResults && vtResults.pois) {
        verticalPois.push(...vtResults.pois);
      }
      if (vtResults && vtResults.pixelScenes) {
        pixelScenes = pixelScenes.concat(vtResults.pixelScenes);
      }
    }
    if (verticalPois.length > 0) {
      combinedPois.push(...verticalPois);
    }

    // Strip imgElement before postMessage. The bytes live in PIXEL_SCENE_DATA
    // on the main thread already; serialising them per-scene was making FF's
    // structured clone take ~30+ seconds on cache-miss generation. Main thread
    // rehydrates imgElement from its own PIXEL_SCENE_DATA[scene.key].
    const slimPixelScenes = pixelScenes.map((s: any) => {
      if (!s) return s;
      // Avoid mutating the underlying telescope object (it's shared with
      // PIXEL_SCENE_DATA records). Return a shallow copy without imgElement.
      const { imgElement: _drop, ...rest } = s;
      return rest;
    });

    // Return the payload back to main thread to apply Wand patching and boss patching
    phase = "posting worker results";
    self.postMessage({
      success: true,
      pw,
      pois: combinedPois,
      pixelScenes: slimPixelScenes
    });
  } catch (error) {
    self.postMessage({
      success: false,
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
      phase,
      pw: e.data.pw,
      fullPixels: !!e.data.fullPixels,
    });
  }
};
